### ISSUE TITLE
Cropped Exercises

### ISSUE THREAD

**Issue by richss** [OpenDSA/OpenDSA#630] opened 2024-10-29 13:44 UTC
My students and I are experiencing issues with many of the exercises being cropped off such that elements toward the right of the exercise are either incompletely shown or cropped out all together.

For example, the mergesort proficiency exercise under "Mergesort Concepts" fails to display all of the problem.  This is not a single issue, but seen throughout the materials.

Note: I have built a custom book on the site and imported it into Canvas.

**Comment by arikorhonen** [comment] 2024-10-29 13:52
Hi,

We have had similar problems. I don’t know if this workaround works with you, but the issues seems to be the initial screen width. I can reproduce the problem if the screen width is too small, but if I widen the browser window and refresh the screen, everything seems to work ok.

Cheers,
Archie

Richard S. Stansbury ***@***.***> kirjoitti 29.10.2024 kello 15.44:



My students and I are experiencing issues with many of the exercises being cropped off such that elements toward the right of the exercise are either incompletely shown or cropped out all together.

For example, the mergesort proficiency exercise under "Mergesort Concepts" fails to display all of the problem. This is not a single issue, but seen throughout the materials.

Note: I have built a custom book on the site and imported it into Canvas.

**Comment by cashaffer** [comment] 2024-10-29 14:28
The problem is with Canvas. They have a 3-column layout and often don't leave enough space for the content column, depending on the window width (and the screen resolution). The best solution usually is to click on the menu icon with the three horizontal lines next to the title to collapse the one menu column.

**Comment by richss** [comment] 2024-10-29 14:29
> similar problems. I don’t know if this workaround works with you, but the issues seems to be the initial screen width. I can reproduce the problem if the screen width is too small, but if I widen the browser window and refresh the screen, everything

I appreciate the input.  I tried, but did not have success.  Despite window size or zoom level, I seemed to have comparable, but not the exact same, amount of cropping.

**Comment by cashaffer** [comment] 2024-10-29 14:32
It is also a lot worse for instructors than for students, since instructors get yet another column to the right of the content. Moving to student view will let you see what the students see (which might still be cropped until you close the menu to the left of the content).

**Closed** 2024-12-15 02:40 UTC
